//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumAnh
    {
        public AlbumAnh()
        {
            this.HinhAnhs = new HashSet<HinhAnh>();
        }
    
        public int ID { get; set; }
        public string TenAlbum { get; set; }
        public string NguoiDang { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<HinhAnh> HinhAnhs { get; set; }
    }
}
