//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDiem
    {
        public DiaDiem()
        {
            this.Tours = new HashSet<Tour>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public string NoiDung { get; set; }
    
        public virtual ICollection<Tour> Tours { get; set; }
    }
}
