//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDataEntities : DbContext
    {
        public TestDataEntities()
            : base("name=TestDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AlbumAnh> AlbumAnhs { get; set; }
        public DbSet<ChucNang> ChucNangs { get; set; }
        public DbSet<DiaDiem> DiaDiems { get; set; }
        public DbSet<GioiThieu> GioiThieux { get; set; }
        public DbSet<HinhAnh> HinhAnhs { get; set; }
        public DbSet<HoSoCongTy> HoSoCongTies { get; set; }
        public DbSet<KhachSan> KhachSans { get; set; }
        public DbSet<PhanQuyen> PhanQuyens { get; set; }
        public DbSet<PhuongTien> PhuongTiens { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Tour> Tours { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
