//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuongTien
    {
        public int ID { get; set; }
        public string TenPhuongTien { get; set; }
        public Nullable<int> ChoNgoi { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string HinhAnh { get; set; }
        public string NoiDung { get; set; }
    }
}
