//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int ID { get; set; }
        public string TenTour { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<decimal> GiaCu { get; set; }
        public Nullable<decimal> GiaMoi { get; set; }
        public string BaiViet { get; set; }
        public string DiemDen { get; set; }
        public Nullable<int> IDDiaDiem { get; set; }
        public Nullable<int> IDKhachSan { get; set; }
    
        public virtual DiaDiem DiaDiem { get; set; }
        public virtual KhachSan KhachSan { get; set; }
    }
}
