//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.PhanQuyens = new HashSet<PhanQuyen>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<PhanQuyen> PhanQuyens { get; set; }
    }
}
