//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDuLich.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoCongTy
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string GioiThieu { get; set; }
        public string DiaChi { get; set; }
        public string Logo { get; set; }
        public string Maso { get; set; }
    }
}
