//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDuLich.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaHang
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string DiaChi { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
    }
}
